# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Sopt28_4th_Seminar' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Sopt28_4th_Seminar
  pod 'Alamofire', '~> 5.2'

end
